"""increase status length to 30

Revision ID: 1be07f9ede1e
Revises: 4367a5d4596a
Create Date: 2026-04-23 13:39:57.073866
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be07f9ede1e'
down_revision: Union[str, None] = '4367a5d4596a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
