"""initial

Revision ID: 31c348e680ee
Revises: 
Create Date: 2026-03-24 16:33:10.111772
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '31c348e680ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('sub_industry', sa.String(length=200), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('restricted_business', sa.Boolean(), nullable=False),
    sa.Column('severe_controversy', sa.Boolean(), nullable=False),
    sa.Column('profile_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index('idx_company_profile_embedding', 'companies', ['profile_embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 20}, postgresql_ops={'profile_embedding': 'vector_cosine_ops'})
    op.create_table('drl_models',
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_path', sa.String(length=500), nullable=True),
    sa.Column('architecture', sa.String(length=50), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('train_sharpe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('test_sharpe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('train_esg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('test_esg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_base_embedding', 'knowledge_base', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 10}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('portfolio_metrics',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('risk_profile', sa.String(length=20), nullable=True),
    sa.Column('esg_priority', sa.String(length=20), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('annual_return', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('annual_volatility', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_esg_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('num_holdings', sa.Integer(), nullable=True),
    sa.Column('sector_count', sa.Integer(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('portfolio_id')
    )
    op.create_table('sector_rankings',
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('company_count', sa.Integer(), nullable=True),
    sa.Column('avg_sharpe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_esg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_volatility', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_return', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('sector', 'as_of_date')
    )
    op.create_table('training_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('chunks_processed', sa.Integer(), nullable=False),
    sa.Column('records_stored', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('computed_metrics',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('annual_return', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('annual_volatility', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sharpe_252d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sortino_252d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('calmar_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('momentum_20d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('momentum_60d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_esg_composite', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_e_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_s_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_g_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('eligible_hard_screen', sa.Boolean(), nullable=True),
    sa.Column('sector_rank_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'as_of_date')
    )
    op.create_table('esg_scores',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('e_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('s_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('g_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date', 'provider')
    )
    op.create_table('portfolio_allocations',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('risk_profile', sa.String(length=20), nullable=False),
    sa.Column('esg_priority', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['drl_models.model_id'], ),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('portfolio_id', 'symbol')
    )
    op.create_table('prices_daily',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_refresh_tokens_token', 'refresh_tokens', ['token'], unique=False)
    op.create_index('idx_refresh_tokens_user', 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_refresh_tokens_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_token', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('prices_daily')
    op.drop_table('portfolio_allocations')
    op.drop_table('esg_scores')
    op.drop_table('computed_metrics')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('training_jobs')
    op.drop_table('sector_rankings')
    op.drop_table('portfolio_metrics')
    op.drop_index('idx_knowledge_base_embedding', table_name='knowledge_base', postgresql_using='ivfflat', postgresql_with={'lists': 10}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('knowledge_base')
    op.drop_table('drl_models')
    op.drop_index('idx_company_profile_embedding', table_name='companies', postgresql_using='ivfflat', postgresql_with={'lists': 20}, postgresql_ops={'profile_embedding': 'vector_cosine_ops'})
    op.drop_table('companies')
    # ### end Alembic commands ###
