"""initial

Revision ID: 886883a7d702
Revises: c1a2b3d4e5f6
Create Date: 2026-04-23 12:22:35.106924
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '886883a7d702'
down_revision: Union[str, None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_allocations_portfolio_id'), table_name='portfolio_allocations')
    op.drop_index(op.f('ix_portfolio_allocations_portfolio_symbol'), table_name='portfolio_allocations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_portfolio_allocations_portfolio_symbol'), 'portfolio_allocations', ['portfolio_id', 'symbol'], unique=False)
    op.create_index(op.f('ix_portfolio_allocations_portfolio_id'), 'portfolio_allocations', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###
